kind = "web"
previewPath = "/"
title = "MineNova"
version = "1.0.0"
id = "artifacts/minenova"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25887

[services.development]
run = "pnpm --filter @workspace/minenova run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/minenova", "run", "build" ]
publicDir = "artifacts/minenova/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25887"
BASE_PATH = "/"
